---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  minReadySeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  serviceName: elasticsearch-data
  replicas: {DATA_NODE_COUNT}
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: {ES_DATA_IMAGE}
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "{CLUSTER_NAME}"
        - name: "DISCOVERY_ZEN_MINIMUM_MASTER_NODES"
          value: "{MASTER_MIN_COUNT}"
        - name: "NODE_MASTER"
          value: "false"
        - name: "NODE_INGEST"
          value: "false"
        - name: "NODE_DATA"
          value: "true"
        - name: "HTTP_ENABLED"
          value: "false"
        - name: "DISCOVERY_ZEN_PING_UNICAST_HOSTS"
          value: "{ELASTICSEARCH_DISCOVERY_SERVICE}"
        - name: "ES_JAVA_OPTS"
          value: "-Xms{ES_DATA_HEAP} -Xmx{ES_DATA_HEAP}"
        resources:
          requests:
            memory: "{DATA_MEMORY}"
            cpu: "{DATA_CPU_COUNT}"
        ports:
        - containerPort: {TRANSPORT_TCP_PORT}
          name: transport
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: {TRANSPORT_TCP_PORT}
          initialDelaySeconds: 600
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: {DATA_NODE_PATH}
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: {DATA_STORAGE_SIZE}
